name: echapopital

services:
  db:
    image: mysql:8.3.0
    container_name: echapopital_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  ia_api:
    image: cedsanc/echapopitalia:latest
    container_name: echap-ia-api
    restart: unless-stopped
    ports:
      - "5001:5001"
    networks:
      - app-net
    volumes:
      - ./ia_data:/app
  app:
    image: cedsanc/echapopitalbackend:latest
    container_name: echapopitalbackend
    depends_on:
      db:
        condition: service_healthy
      ia_api:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      IA_API_URL: http://ia_api:5001/generate
    ports:
      - "8081:8081"
    networks:
      - app-net

  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: echap-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-net

  watchtower:
    image: containrrr/watchtower
    container_name: echap-watchtower
    restart: unless-stopped
    command: --interval 300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  db_data: